### ISSUE TITLE
Please help to import sequence.fasta file from NCBI

### ISSUE THREAD

**Issue by langse62171** [MaestSi/MetONTIIME#14] opened 2020-04-07 16:10 UTC
Hello, first of all thank you for the MetONTIIME pipeline. 
The script "install.sh" ran without any error message. The import of SILVA_132 with "qiime tools import" also worked wll. If I run the script "Importing_database.sh" now, I get the following error message:
#
./Import_database.sh /home/sysadmin/NCBI33175/sequence.fasta
#
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

Package Plan ##

  environment location: /home/sysadmin/miniconda3/envs/entrez_qiime_env

  added / updated specs:
    - gcc
    - python=2.7

The following NEW packages will be INSTALLED:

  ca-certificates    anaconda/linux-64::ca-certificates-2020.1.1-0
  certifi            anaconda/linux-64::certifi-2019.11.28-py27_0
  cloog              anaconda/linux-64::cloog-0.18.0-0
  gcc                anaconda/linux-64::gcc-4.8.5-7
  gmp                anaconda/linux-64::gmp-6.1.2-hb3b607b_0
  isl                anaconda/linux-64::isl-0.12.2-0
  libedit            anaconda/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             anaconda/linux-64::libffi-3.2.1-h4deb6c0_3
  libgcc-ng          anaconda/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       anaconda/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  mpc                anaconda/linux-64::mpc-1.1.0-h10f8cd9_1
  mpfr               anaconda/linux-64::mpfr-4.0.1-hdf1c602_3
  ncurses            anaconda/linux-64::ncurses-6.2-he6710b0_0
  openssl            anaconda/linux-64::openssl-1.1.1-h7b6447c_0
  pip                anaconda/linux-64::pip-19.3.1-py27_0
  python             anaconda/linux-64::python-2.7.17-h9bab390_0
  readline           anaconda/linux-64::readline-7.0-h7b6447c_5
  setuptools         anaconda/linux-64::setuptools-44.0.0-py27_0
  sqlite             anaconda/linux-64::sqlite-3.31.1-h7b6447c_0
  tk                 anaconda/linux-64::tk-8.6.8-hbc83047_0
  wheel              anaconda/linux-64::wheel-0.33.6-py27_0
  zlib               anaconda/linux-64::zlib-1.2.11-h7b6447c_3

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'anaconda::gcc-4.8.5-7'.
Rolling back transaction: done

LinkError: post-link script failed for package anaconda::gcc-4.8.5-7
location of failed script: /home/sysadmin/miniconda3/envs/entrez_qiime_env/bin/.gcc-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Installation failed: gcc is not able to compile a simple 'Hello, World' program.

stderr: No LSB modules are available.
/home/sysadmin/miniconda3/envs/entrez_qiime_env/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory

return code: 1

()

Requirement already satisfied: numpy in /home/sysadmin/miniconda3/lib/python3.7/site-packages (1.18.2)
Collecting cogent
  Using cached cogent-1.9.tar.gz (1.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/sysadmin/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x3su186b/cogent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x3su186b/cogent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-x3su186b/cogent/pip-egg-info
         cwd: /tmp/pip-install-x3su186b/cogent/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x3su186b/cogent/setup.py", line 61
        print "Failed to build html due to ImportErrors for sphinx"
                                                                  ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed to build html due to ImportErrors for sphinx")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  File "./entrez_qiime/entrez_qiime.py", line 192
    print "Need to supply either FASTA file or accession number list as input."    # should never get here because either -i or -L is a required argument.
                                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Need to supply either FASTA file or accession number list as input."    # should never get here because either -i or -L is a required argument.)?
Imported /home/sysadmin/NCBI33175/sequence.fasta as DNAFASTAFormat to /home/sysadmin/NCBI33175/sequence_sequence.qza
Usage: qiime tools import [OPTIONS]

  Import data to create a new QIIME 2 Artifact. See
  https://docs.qiime2.org/ for usage examples and details on the file
  types and associated semantic types that can be imported.

Options:
  --type TEXT             The semantic type of the artifact that will
                          be created upon importing. Use
                          --show-importable-types to see what importable
                          semantic types are available in the current
                          deployment.                         [required]
  --input-path PATH       Path to file or directory that should be
                          imported.                           [required]
  --output-path ARTIFACT  Path where output artifact should be written.
                                                              [required]
  --input-format TEXT     The format of the data to be imported. If not
                          provided, data must be in the format expected
                          by the semantic type provided via --type.
  --show-importable-types Show the semantic types that can be supplied
                          to --type to import data into an artifact.
  --show-importable-formats
                          Show formats that can be supplied to
                          --input-format to import data into an
                          artifact.
  --help                  Show this message and exit.

                    There was a problem with the command:                     
 (1/1) Invalid value for "--input-path": Path
  "/home/sysadmin/NCBI33175/sequence_accession_taxonomy.txt" does not exist.
sysadmin@BI:~/MetONTIIME$ 
#
Even if I try to install gcc separately with "conda install gcc" I get the same error message:
#
Collecting package metadata (current_repodata.json): done
Solving environment: done

Package Plan ##

  environment location: /home/sysadmin/miniconda3

  added / updated specs:
    - gcc

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py37_1         156 KB  anaconda
    conda-4.8.3                |           py37_0         3.0 MB  anaconda
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following NEW packages will be INSTALLED:

  cloog              anaconda/linux-64::cloog-0.18.0-0
  gcc                anaconda/linux-64::gcc-4.8.5-7
  gmp                anaconda/linux-64::gmp-6.1.2-hb3b607b_0
  isl                anaconda/linux-64::isl-0.12.2-0
  mpc                anaconda/linux-64::mpc-1.1.0-h10f8cd9_1
  mpfr               anaconda/linux-64::mpfr-4.0.1-hdf1c602_3

The following packages will be UPDATED:

  openssl              pkgs/main::openssl-1.1.1f-h7b6447c_0 --> anaconda::openssl-1.1.1-h7b6447c_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates                                 pkgs/main --> anaconda
  certifi                                         pkgs/main --> anaconda
  conda                                           pkgs/main --> anaconda

Proceed ([y]/n)? y

Downloading and Extracting Packages
certifi-2019.11.28   | 156 KB    | ############################### | 100% 
conda-4.8.3          | 3.0 MB    | ############################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'anaconda::gcc-4.8.5-7'.
Rolling back transaction: done

LinkError: post-link script failed for package anaconda::gcc-4.8.5-7
location of failed script: /home/sysadmin/miniconda3/bin/.gcc-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Installation failed: gcc is not able to compile a simple 'Hello, World' program.

stderr: No LSB modules are available.
/home/sysadmin/miniconda3/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory

return code: 1

()
#
when i run "conda env list" i get:
#
conda environments:
base                  *  /home/sysadmin/miniconda3
MetONTIIME_env           /home/sysadmin/miniconda3/envs/MetONTIIME_env
entrez_qiime_env         /home/sysadmin/miniconda3/envs/entrez_qiime_env
qiime2-2020.2            /home/sysadmin/miniconda3/envs/qiime2-2020.2

#
When I searched the net for this I could not find anything, so I ask for help here. If you need further information please let me know.

**Comment by MaestSi** [comment] 2020-04-07 17:12
Hi, I found a similar issue [here](https://github.com/ContinuumIO/anaconda-issues/issues/1392). Apparently someone solved it by adding line `allow_softlinks: False` to .condarc file with something like:
` echo "allow_softlinks: False" | cat - /home/sysadmin/.condarc > /tmp/out && mv /tmp/out /home/sysadmin/.condarc`.
I tried to reproduce your issue removing **entrez_qiime_env** environment and repeating the installation from scratch. It installed exactly the same versions you listed, but it worked successfully, so I was not able to reproduce it. My guess is that you may have some environmental variables set that don't allow gcc to work correctly.
First of all I would try this: open file **Import_database.sh** and replace *gcc* with  *gcc_linux-64*. Then try rerunning the script and let me know.
Simone

**Comment by langse62171** [comment] 2020-04-07 18:47
Hi Simon. Thanks a lot for your quick response, the change in **Import_database.sh** to gcc_linux-64 worked. Setting up entrez_qiime_env and creating the files **sequence_sequnze.qza** and **sequence_taxonomy.qza** now worked without errors. 

Now I have one more question. In the meantime I have run the pipeline with the enclosed test file "Test_BC04_xxx.zip" and the SILVA database. According to logfile.txt the pipeline is finished. All files in the folders "analysis, basecalling, preprocessing and qc" seem to have been created. Only the files **taxa-bar-plots.qzv** and **taxa-bar-plots-no-Unassigned.qzv** in the analysis folder are missing. Therefore I ask for help here, too. What could be the reason for this? 

In the nohup.out file is several times deposited that no metadata file is present. I did not specify this file in the config_MinION_mobile_lab.R. Could that possibly be the reason?

Best regards, Sebastian

**Comment by MaestSi** [comment] 2020-04-07 18:53
Yes, you must specify the path to a file. In the **config_MinION_mobile_lab.R** file you may set:
`SAMPLE_METADATA <- "/home/sysadmin/sample-metadata.tsv"`
Let me know if it works!
Simone

**Comment by langse62171** [comment] 2020-04-08 11:42
Hi and many thanks again! It works now after just adding a path :-)
Best 
Sebastian

**Comment by MaestSi** [comment] 2020-04-08 11:54
Good! I am going to close the issue. Feel free to open another one if you need any other clarifications.
Best,
Simone

**Closed by MaestSi** 2020-04-08 11:54 UTC
Labels: bug
